### ISSUE TITLE
Douglas Code Review

### ISSUE THREAD

**Issue by thejohnhoffer** [thejohnhoffer/minerva-scripts#2]
Config only needs this:
```
main:
    TIME: *
    LOD: *
    RANGES: [[*, *]..]
    COLORS: [[*, *]..]
```
- input and output only command-line
    - no option to add current date to path
    - output default to `pathlib.Path.cwd()`
    - no input default, required argument
    - remove [parser](https://github.com/thejohnhoffer/minerva-scripts/blob/master/src/minerva_scripts/helper/parser.py), uee pathlib
